### ISSUE TITLE
About passing template parameters

### ISSUE THREAD

**Issue by kreja** [coditorium/nodejs-swig-loader#1]
I tried this and got the right html string:

```
var tmpl = require('swig!./swigtest.swig?person=John');
console.log(tmpl);
```

My question is.. can I pass template parameters like this:

```
var tmpl = require('swig!./swigtest.swig');
console.log(tmpl({person:'John'}));
```

**Comment by pmendelski** [comment]
At the moment it's impossible. This loader executes Swig during Webpack compilation only. I added an enhancement request for that: https://github.com/coditorium/nodejs-swig-loader/issues/3.

I would happily merge a pull request :wink:
