### ISSUE TITLE
Webpack 2 support

### ISSUE THREAD

**Issue by CoenWarmer** [coditorium/nodejs-swig-loader#7]
When using swig-loader on a Webpack 2 installation, Webpack throws build errors when importing swig files.

Error message:

```
Module build failed: TypeError: Cannot set property query of #<Object> which has only a getter
    at Object.module.exports (/Users/coenwarmer/Development/zaaksysteem/client/node_modules/swig-loader/lib/swig-loader.js:15:15)
```

Webpack config:
```
module: {
	rules: [
		{
			test: /\.swig$/,
			use: [
				{
					loader: 'swig-loader'
				}
			],
			exclude: /node_modules/
		}
	]
}
```

**Comment by CoenWarmer** [comment]
The block line 15 is in is this one:

```
module.exports = function(content) {
	var plugin = this;
	plugin.cacheable && plugin.cacheable();
	plugin.query = loaderUtils.parseQuery(this.query); <------ this line causes the issue
	plugin.resourceQuery = loaderUtils.parseQuery(this.resourceQuery);
	content = resolve(content, plugin);
	return prepareResult(content, plugin.query);
};
```
When I remove that line my build seems to be succeeding. But I'm not sure if something else will break as a result, so I'd much rather make sure the plugin is fully upgraded to Webpack 2.

Maybe @TheLarkInn could shine a light?

**Comment by pmendelski** [comment]
Hi. Sorry for not responding faster.

Try changing that line and run tests. There are plenty of them. I will gladly accept a pull request :)

**Comment by CoenWarmer** [comment]
Hey @mendlik, sorry for my turn to not respond sooner ;) Wanted to wait a bit for Webpack 2 to mature. We're now attempting to migrate and so we need this to work. 
I will start working on a PR for Webpack 2 support now.

**Comment by pmendelski** [comment]
Hi @CoenWarmer I will give your PR a warm welcome ;)

**Comment by CoenWarmer** [comment]
And here it is :) https://github.com/coditorium/nodejs-swig-loader/pull/8
