### ISSUE TITLE
Get a string if passed single bracketed array to template

### ISSUE THREAD

**Issue by PeachScript** [coditorium/nodejs-swig-loader#9]
If I passed a single bracketed array like this to the template file:

```js
test.swig?test[]=test1
```

I will get a string `{ test: "test1" }` rather than `{ test: ["test1"] }` in the template, this is a known issue of [query-string](https://github.com/sindresorhus/query-string/issues/88), and it has been fixed in [`v4.3.3`](https://github.com/sindresorhus/query-string/commit/8d601e64f31d7c9c23c0882945237ead63705b78).

So could you upgrade the version of `query-string` in dependencies(maybe use `^4.3.3` is better?) and release a new version to fix it?

**Comment by pmendelski** [comment]
Sorry I no longer develop this loader. I will gladly accept a PR and release a new version.

**Comment by PeachScript** [comment]
Okay, I have already create a PR #10 .

**Comment by pmendelski** [comment]
Thanks for your PR. It's merged and released in version 2.1.0. Cheers!

Sorry for taking so long to release it.
